#!/bin/sh

cp -r ${BENDER_RESOURCE}/gpl.txt .
cp -r ${BENDER_RESOURCE}/win32-shared-qt .
cp -r ${BENDER_RESOURCE}/win32-shared-openssl .
cp -r ${BENDER_RESOURCE}/xivoicon.ico .
cp -r ${BENDER_RESOURCE}/xivoicon_un.ico .
cp -r ${BENDER_RESOURCE}/xivo.bmp .
mv work win32-shared

cat > installer.nsi <<!
!define XIVO_VERSION ${XIVO_VERSION}
!define SVN_VERSION ${SVN_VERSION}
!define FULLVERSION "${XIVO_VERSION} (svn ${SVN_VERSION})"

SetCompressor /FINAL /SOLID lzma

!define MULTIUSER_EXECUTIONLEVEL Highest
!define MULTIUSER_MUI
!include MultiUser.nsh
!include "MUI2.nsh"
!define MUI_ICON "xivoicon.ico"
!define MUI_UNICON "xivoicon_un.ico"
!define MUI_HEADERIMAGE
  !define MUI_HEADERIMAGE_BITMAP xivo.bmp
  !define MUI_HEADERIMAGE_UNBITMAP xivo.bmp


Name "XiVO Client \${FULLVERSION}"
OutFile "xivoclient-inst.exe"

InstallDir \$PROGRAMFILES\XiVO\

; Request application privileges for Windows Vista
RequestExecutionLevel admin
ShowInstDetails show
ShowUninstDetails show

!insertmacro MULTIUSER_PAGE_INSTALLMODE
!define MUI_PAGE_HEADER_SUBTEXT \$(XIVO_LICENSE_TEXT)
!insertmacro MUI_PAGE_LICENSE gpl.txt

!define MUI_PAGE_HEADER_TEXT \$(OPENSSL_LICENSE_TEXT)
!define MUI_PAGE_HEADER_SUBTEXT 

!insertmacro MUI_PAGE_LICENSE win32-shared-openssl\openssl-license.txt
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
Var Dialog
Var CheckboxShortcutDesktop
Var CheckboxShortcutStart
Var CheckboxShortcutDesktopState
Var CheckboxShortcutStartState

Page custom installMiscPage installMiscPageLeave ;Custom page

Function installMiscPage
  !insertmacro MUI_HEADER_TEXT \$(MISC_PAGE_TITLE) \$(MISC_PAGE_SUBTITLE)
  nsDialogs::Create 1018
  Pop \$Dialog
  
  \${If} \$Dialog == error
  	Abort
  \${EndIf}

  \${NSD_CreateCheckbox} 0 10u 100% 10u "&Add a Shortcut on desktop"
  Pop \$CheckboxShortcutDesktop

  \${NSD_CreateCheckbox} 0 25u 100% 10u "&Add a Shortcut in start menu"
  Pop \$CheckboxShortcutStart

  \${NSD_Check} \$CheckboxShortcutDesktop
  \${NSD_Check} \$CheckboxShortcutStart

  nsDialogs::Show

FunctionEnd

Function installMiscPageLeave
  \${NSD_GetState} \$CheckboxShortcutDesktop \$CheckboxShortcutDesktopState
  \${NSD_GetState} \$CheckboxShortcutStart \$CheckboxShortcutStartState
FunctionEnd

!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

;Languages
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "French"

Function .onInit
  !insertmacro MULTIUSER_INIT
  !insertmacro MUI_LANGDLL_DISPLAY

FunctionEnd

!define REG_UNINST Software\Microsoft\Windows\CurrentVersion\Uninstall\xivoclient

; The stuff to install
Section "Qt libraries" QtLib ; components page
  SectionIn RO
  SetOutPath \$INSTDIR
  
  File /r win32-shared-qt\*
SectionEnd ; end the section

Section "OpenSSL libraries" OpensslLib ; components page
  SectionIn RO
  SetOutPath \$INSTDIR

  File /r win32-shared-openssl\*
SectionEnd ; end the section

Section "Xivoclient executable" XivoclientExe ; components page
  SectionIn RO
  SetOutPath \$INSTDIR
  
  File /r win32-shared\*

  WriteRegStr HKLM "Software\XiVO\xivoclient" "Install_Dir" "\$INSTDIR"
  WriteRegStr HKLM "\${REG_UNINST}" "DisplayName" "XiVO Client"
  WriteRegStr HKLM "\${REG_UNINST}" "UninstallString" '"\$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKLM "\${REG_UNINST}" "NoModify" 1
  WriteRegDWORD HKLM "\${REG_UNINST}" "NoRepair" 1
  WriteUninstaller "\$INSTDIR\uninstall.exe"
  # Associate with tel: and callto: protocol
  WriteRegStr HKCR "tel" "" "URL:tel Protocol"
  WriteRegStr HKCR "tel" "URL Protocol" ""
  WriteRegStr HKCR "tel\shell\open\command" "" "\$INSTDIR\xivoclient.exe %1"
  WriteRegStr HKCR "callto" "" "URL:callto Protocol"
  WriteRegStr HKCR "callto" "URL Protocol" ""
  WriteRegStr HKCR "callto\shell\open\command" "" "\$INSTDIR\xivoclient.exe %1"

  \${If} \$CheckboxShortcutDesktopState == \${BST_CHECKED}
    CreateShortCut "\$DESKTOP\xivoclient.lnk"  "\$INSTDIR\xivoclient.exe"
  \${EndIf}

  \${If} \$CheckboxShortcutStartState == \${BST_CHECKED}
     CreateDirectory "\$SMPROGRAMS\XiVO"
     CreateShortCut "\$SMPROGRAMS\XiVO\\\$(START_XIVOCLIENT)"  "\$INSTDIR\xivoclient.exe"
     CreateShortCut "\$SMPROGRAMS\XiVO\\\$(REMOVE_XIVOCLIENT)"  "\$INSTDIR\uninstall.exe"
  \${EndIf}
SectionEnd ; end the section



Section "Uninstall"
  SetShellVarContext all
  ; remove any shortcut
  Delete "\$DESKTOP\xivoclient.lnk"
  Delete "\$SMPROGRAMS\XiVO\*"
  RmDir "\$SMPROGRAMS\XiVO"
  ; remove the uri association
  DeleteRegKey HKLM \${REG_UNINST} 
  DeleteRegKey HKLM "Software\XiVO\xivoclient"
  DeleteRegKey HKCR "tel"
  DeleteRegKey HKCR "callto"
  ; remove the program dir
  Delete \$INSTDIR\uninstall.exe
  Delete \$INSTDIR\imageformats\*.dll
  Delete \$INSTDIR\sqldrivers\*.dll
  Delete \$INSTDIR\plugins\*.dll
  RMDir \$INSTDIR\imageformats
  RMDir \$INSTDIR\sqldrivers
  RMDir \$INSTDIR\plugins
  Delete \$INSTDIR\*.dll
  Delete \$INSTDIR\*.txt
  Delete \$INSTDIR\*.exe
  RMDir \$INSTDIR

SectionEnd ; end the section

Function un.onInit
  !insertmacro MUI_UNGETLANGUAGE
FunctionEnd

LangString SuccessInstall \${LANG_ENGLISH}  "The installation was successful, do you want to start the xivoclient right now ?"
LangString SuccessInstall \${LANG_FRENCH}  "L'installation a réussi, voulez-vous lancer le xivoclient maintenant ?"

Function .onInstSuccess
  MessageBox MB_YESNO  \$(SuccessInstall) /SD IDNO IDNO NoReadme
  ExecShell "open" \$INSTDIR/xivoclient.exe
  NoReadme:
FunctionEnd

;Language strings

LangString XIVO_LICENSE_TEXT \${LANG_ENGLISH} "XiVO Client is licensed under the GNU GPLv3 with a special exception to allow the link with OpenSSL."
LangString XIVO_LICENSE_TEXT \${LANG_FRENCH}  "XiVO Client est distribué sous licence GNU GPLv3 avec une exception particulière vous autorisant à le lier à OpenSSL."

LangString OPENSSL_LICENSE_TEXT \${LANG_ENGLISH} "OpenSSL license"
LangString OPENSSL_LICENSE_TEXT \${LANG_FRENCH}  "Licence d'OpenSSL"

LangString DESC_QtLib \${LANG_ENGLISH} "Qt libraries ( cross-platform application and UI framework )"
LangString DESC_QtLib \${LANG_FRENCH}  "Bibliothèque Qt (framework multi platforme gérant l'IHM, le réseau, ...) "

LangString DESC_xivoclientExe \${LANG_ENGLISH} "Xivoclient executable"
LangString DESC_xivoclientExe \${LANG_FRENCH}  "Éxecutable xivoclient"

LangString DESC_OpensslLib \${LANG_ENGLISH} "OpenSSL libraries ( cryptography )"
LangString DESC_OpensslLib \${LANG_FRENCH}  "Bibliothèque OpenSSL ( cryptographie )"

LangString MISC_PAGE_TITLE \${LANG_ENGLISH} "Miscellaneous.."
LangString MISC_PAGE_TITLE \${LANG_FRENCH}  "Divers.."

LangString MISC_PAGE_SUBTITLE \${LANG_ENGLISH} "Glory to the hypnotoad"
LangString MISC_PAGE_SUBTITLE \${LANG_FRENCH}  "Gloire au crapaud hypnotiseur"

LangString START_XIVOCLIENT \${LANG_ENGLISH} "start xivoclient \${FULLVERSION}.lnk"
LangString START_XIVOCLIENT \${LANG_FRENCH}  "lancer xivoclient \${FULLVERSION}.lnk"

LangString REMOVE_XIVOCLIENT \${LANG_ENGLISH} "Remove xivoclient \${FULLVERSION}.lnk"
LangString REMOVE_XIVOCLIENT \${LANG_FRENCH}  "Désinstaller xivoclient \${FULLVERSION}.lnk"

;Assign language strings to sections
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT \${QtLib} \$(DESC_QtLib)
  !insertmacro MUI_DESCRIPTION_TEXT \${XivoclientExe} \$(DESC_xivoclientExe)
  !insertmacro MUI_DESCRIPTION_TEXT \${OpensslLib} \$(DESC_OpensslLib)
!insertmacro MUI_FUNCTION_DESCRIPTION_END

VIProductVersion "1.0.0.33"
VIAddVersionKey /LANG=\${LANG_ENGLISH} "ProductName" "Xivoclient installer"
VIAddVersionKey /LANG=\${LANG_ENGLISH} "Comments" "Xivoclient, phone helper"
VIAddVersionKey /LANG=\${LANG_ENGLISH} "FileDescription" "Xivoclient, phone helper installer"
VIAddVersionKey /LANG=\${LANG_ENGLISH} "FileVersion" "1"
VIAddVersionKey /LANG=\${LANG_ENGLISH} "LegalCopyright" "© Bender Bending Rodríguez"
!

wine /woot/Unicode/makensis.exe installer.nsi
cp xivoclient-inst.exe ${BUILT_DIR}/xivoclient-${XIVO_VERSION}-${SVN_VERSION}.exe

