#!/bin/sh

TARGET_HOST=maclab@maclab
TARGET_SVN_VERSION=1.6

set_up_build_dir

make_the_build <<!
  export PATH="/opt/qt-4.6.3-shared/bin:\$PATH"
  QMAKE="/opt/qt-4.6.3-shared/bin/qmake -macx" \
  JOPT=-j3 \
  make all-linux

  cd ./bin/

  sed -e "s/Created by Qt\/QMake/Created by Proformatique/g" \
      -e "s/com\.yourcompany\.xivoclient/com.proformatique.xivoclient/g" \
      -e "s/appli\.rc/xivo.icms/g" < ./xivoclient.app/Contents/Info.plist > plop

  cat plop > ./xivoclient.app/Contents/Info.plist
  
  sips -s format icns ../images/xivoicon.ico --out xivoclient.app/Contents/Resources/xivo.icms
  rm ./xivoclient.app/Contents/Resources/appli.rc
  
  macdeployqt xivoclient.app
  
  install_name_tool -change libxivoclientbaselib.1.dylib \
                            @executable_path/libxivoclientbaselib.1.dylib \
                            ./xivoclient.app/Contents/MacOS/xivoclient

  install_name_tool -change /opt/qt-4.6.3-shared/lib/QtGui.framework/Versions/4/QtGui \
                            @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui \
                            libxivoclientbaselib.dylib
  install_name_tool -change /opt/qt-4.6.3-shared/lib/QtNetwork.framework/Versions/4/QtNetwork \
                            @executable_path/../Frameworks/QtNetwork.framework/Versions/4/QtNetwork \
                            libxivoclientbaselib.dylib
  install_name_tool -change /opt/qt-4.6.3-shared/lib/QtCore.framework/Versions/4/QtCore \
                            @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore \
                            libxivoclientbaselib.dylib
  
  cp -R *dylib  ./xivoclient.app/Contents/MacOS
  
  macdeployqt xivoclient.app -dmg
!
fetch_built_files xivoclient.dmg
remove_build_dir 

exit 0;
