#!/bin/sh
TARGET_HOST=debian-lenny-i386
TARGET_SVN_VERSION=1.5

set_up_build_dir

make_the_build <<!
  JOPT=-j3 QMAKE=/opt/qt-4.6.3-shared/bin/qmake make all-linux
  find bin -name ".svn" | xargs rm -rf
!

fetch_built_files
remove_build_dir 
