######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 22 14:29:39 2010
######################################################################

TEMPLATE = app
TARGET = unit-test
DEPENDPATH += . src
INCLUDEPATH += . src utest
LIBS +=

system(lemon src/grammar.ly;mv src/grammar.c src/grammar.cpp)
# Input
HEADERS += src/*.h utest/*.h
SOURCES += src/*.cpp utest/*.cpp
